### Register a new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "testuser3",
  "password": "testpassword"
}

### Get all users
GET http://localhost:3000/api/users

### Login user
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "madde20",
  "password": "12345678"
}
  
### Logout user
DELETE http://localhost:3000/api/users/logout

### Get session
GET http://localhost:3000/api/users/session


### Post new post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "Hello world",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. se of Letraset",
  "author": "6446fcdb682a42931a1822fa"
}

### Get all posts

GET http://localhost:3000/api/posts

### Delete a post
DELETE http://localhost:3000/api/posts/6447c1945e914780c59b33a7


### Promote user to admin
PUT http://localhost:3000/api/users/644273b3979df454b9353c9c
Content-Type: application/json

{
  "isAdmin": true
}

### Delete user
DELETE http://localhost:3000/api/users/644273b3979df454b9353c9c

### PUT a post
PUT http://localhost:3000/api/posts/644a3388fcf9b7590be23d76
Content-Type: application/json

{
  "_id": "644a3388fcf9b7590be23d76",
  "title": "Hello world",
  "author": "6447b520e9a92ca45b05c146",
  "content": "New content here",
  "createdAt": "2023-04-27T08:34:16.438Z"
}

